server:
 port: 8095
 
spring:
 datasource:
  url: jdbc:mysql://localhost:3306/RMS
  username: root
  password: Chandan@123
  driver-class-name: com.mysql.cj.jdbc.Driver
 
 jpa:
  hibernate:
   ddl-auto: update
  show-sql: true
  database-platform: org.hibernate.dialect.MySQL8Dialect
 
 application:
  name: userDetails