server:
  port: 8088

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rmsdb
    username: root
    password: Chandan@123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true